<template>
  <div class="feige-module feige-legacy-page">
    <el-alert title="待财务审核用于核验新单收款，不是重复录单表单。审核通过后订单进入服务办理。" type="info" :closable="false" show-icon style="margin-bottom:16px" />
    <section class="content-card">
      <div class="filter-bar"><el-input v-model="filters.keyword" class="filter-keyword" clearable placeholder="订单编号或公司名称" :prefix-icon="Search" @keyup.enter="search" /><el-select v-model="filters.salesmanId" class="filter-select" clearable placeholder="业务人员"><el-option v-for="item in staff" :key="item.id" :label="item.name" :value="item.id" /></el-select><el-select v-model="filters.auditStatus" class="filter-select" clearable placeholder="审核状态"><el-option label="待审核" value="pending" /><el-option label="已通过" value="approved" /><el-option label="已驳回" value="rejected" /></el-select><div class="filter-actions"><el-button type="primary" :icon="Search" @click="search">查询</el-button><el-button @click="reset">重置</el-button><el-button :icon="Refresh" @click="loadRows">刷新</el-button></div></div>
      <div class="status-tabs"><el-radio-group v-model="filters.auditStatus" @change="search"><el-radio-button value="pending">待审核</el-radio-button><el-radio-button value="approved">已通过</el-radio-button><el-radio-button value="rejected">已驳回</el-radio-button><el-radio-button value="">全部</el-radio-button></el-radio-group></div>
      <div class="table-wrap"><el-table v-loading="loading" :data="rows" row-key="id" empty-text="当前没有待审核新单"><el-table-column label="订单编号" width="190"><template #default="{ row }"><strong>{{ row.orderNo }}</strong></template></el-table-column><el-table-column label="公司名称" min-width="240" show-overflow-tooltip><template #default="{ row }"><div class="customer-name">{{ row.companyName }}</div></template></el-table-column><el-table-column label="业务人员" width="130" prop="salesmanName" /><el-table-column label="业务类型" width="145"><template #default="{ row }">{{ optionLabel(businessTypes, row.businessType) }}</template></el-table-column><el-table-column label="订单金额" width="140" align="right"><template #default="{ row }"><strong class="money">{{ money(row.contractAmount) }}</strong></template></el-table-column><el-table-column label="审核状态" width="120" align="center"><template #default="{ row }"><el-tag :type="auditType(row.auditStatus)">{{ auditLabel(row.auditStatus) }}</el-tag></template></el-table-column><el-table-column label="提交时间" width="175"><template #default="{ row }">{{ formatDateTime(row.createTime) }}</template></el-table-column><el-table-column label="审核信息" min-width="190" show-overflow-tooltip><template #default="{ row }"><div>{{ row.auditorName || '-' }}</div><div class="sub-text">{{ row.auditRemark || '暂无审核意见' }}</div></template></el-table-column><el-table-column label="操作" width="160" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openDetail(row)">详情</el-button><el-button v-if="row.auditStatus === 'pending'" link type="success" @click="openAudit(row)">收银审核</el-button></template></el-table-column></el-table></div>
      <div class="pagination-row"><el-pagination v-model:current-page="page.pageNum" v-model:page-size="page.pageSize" :total="page.total" :page-sizes="[10,20,50]" layout="total, prev, pager, next, sizes" @change="loadRows" /></div>
    </section>
    <OrderDetailDrawer v-model="detailVisible" :order="current" />
    <el-dialog v-model="auditVisible" width="min(680px, 94vw)" title="新单收银审核" destroy-on-close><template v-if="current"><el-descriptions :column="2" border><el-descriptions-item label="订单编号">{{ current.orderNo }}</el-descriptions-item><el-descriptions-item label="业务人员">{{ current.salesmanName }}</el-descriptions-item><el-descriptions-item label="客户名称" :span="2">{{ current.companyName }}</el-descriptions-item><el-descriptions-item label="合同金额">{{ money(current.contractAmount) }}</el-descriptions-item><el-descriptions-item label="实收金额">{{ money(current.receivedAmount) }}</el-descriptions-item><el-descriptions-item label="收款账户">{{ current.collectionAccountNumber || '-' }}</el-descriptions-item><el-descriptions-item label="收款时间">{{ formatDateTime(current.collectionTime) }}</el-descriptions-item></el-descriptions><el-form label-position="top" style="margin-top:18px"><el-form-item label="审核结果" required><el-radio-group v-model="auditForm.result"><el-radio-button value="approved">审核通过</el-radio-button><el-radio-button value="rejected">审核驳回</el-radio-button></el-radio-group></el-form-item><el-form-item label="审核意见"><el-input v-model="auditForm.remark" type="textarea" :rows="4" maxlength="500" show-word-limit placeholder="通过可填写核验说明；驳回请写清补充要求" /></el-form-item></el-form></template><template #footer><el-button @click="auditVisible=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submitAudit">确认审核</el-button></template></el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { Refresh, Search } from '@element-plus/icons-vue'
import type { FeigeOrder, StaffOption } from '@/api/feige-order-contract'
import { businessTypes, formatDateTime, money, optionLabel } from './options'
import { feigeOrderData } from '@feige-order-data-source'
import OrderDetailDrawer from './components/OrderDetailDrawer.vue'
const loading = ref(false); const submitting = ref(false); const rows = ref<FeigeOrder[]>([]); const staff = ref<StaffOption[]>([]); const current = ref<FeigeOrder | null>(null); const detailVisible = ref(false); const auditVisible = ref(false)
const filters = reactive({ keyword: '', salesmanId: undefined as number | undefined, auditStatus: 'pending' }); const page = reactive({ pageNum: 1, pageSize: 10, total: 0 }); const auditForm = reactive<{ result: 'approved' | 'rejected'; remark: string }>({ result: 'approved', remark: '' })
async function loadRows() { loading.value = true; try { const data = await feigeOrderData.auditOrders({ pageNum: page.pageNum, pageSize: page.pageSize, keyword: filters.keyword || undefined, salesmanId: filters.salesmanId, auditStatus: filters.auditStatus || undefined }); rows.value = data.records || []; page.total = Number(data.total || 0) } finally { loading.value = false } }
function search() { page.pageNum = 1; loadRows() } function reset() { Object.assign(filters, { keyword: '', salesmanId: undefined, auditStatus: 'pending' }); search() }
async function openDetail(row: FeigeOrder) { current.value = await feigeOrderData.order(row.id); detailVisible.value = true }
function openAudit(row: FeigeOrder) { current.value = row; Object.assign(auditForm, { result: 'approved', remark: '' }); auditVisible.value = true }
async function submitAudit() { if (!current.value) return; if (auditForm.result === 'rejected' && !auditForm.remark.trim()) return ElMessage.warning('驳回订单时请填写审核意见'); submitting.value = true; try { await feigeOrderData.auditOrder(current.value.id, auditForm); ElMessage.success(auditForm.result === 'approved' ? '新单审核已通过' : '新单已驳回'); auditVisible.value = false; await loadRows() } finally { submitting.value = false } }
function auditLabel(value?: string) { return ({ pending: '待审核', approved: '已通过', rejected: '已驳回' } as Record<string,string>)[value || ''] || '待审核' } function auditType(value?: string) { return value === 'approved' ? 'success' : value === 'rejected' ? 'danger' : 'warning' }
onMounted(async () => { staff.value = await feigeOrderData.staffOptions(); await loadRows() })
</script>
<style lang="scss" src="./module.scss"></style>
