<template>
  <div class="feige-module feige-legacy-page">
    <section class="content-card"><div class="filter-bar"><el-input v-model="filters.keyword" class="filter-keyword" clearable placeholder="订单编号或公司名称" :prefix-icon="Search" @keyup.enter="search" /><el-select v-model="filters.status" class="filter-select" clearable placeholder="全部状态"><el-option v-for="item in refundStatuses" :key="item.value" :label="item.label" :value="item.value" /></el-select><el-date-picker v-model="filters.dates" class="filter-date" type="daterange" value-format="YYYY-MM-DD" start-placeholder="申请开始" end-placeholder="申请结束" /><div class="filter-actions"><el-button type="primary" :icon="Search" @click="search">查询</el-button><el-button @click="reset">重置</el-button><el-button :icon="Refresh" @click="loadRows">刷新</el-button></div></div>
      <div class="table-wrap legacy-wide-table"><el-table v-loading="loading" :data="rows" row-key="id" empty-text="暂无退费订单"><el-table-column label="订单编号" width="190" fixed="left"><template #default="{ row }"><strong>{{ row.orderNo }}</strong></template></el-table-column><el-table-column label="申请时间" width="170"><template #default="{ row }">{{ formatDateTime(row.createTime) }}</template></el-table-column><el-table-column label="业务人员" width="130" prop="salesmanName" /><el-table-column label="所属团队" width="145"><template #default="{ row }">{{ row.teamName || '-' }}</template></el-table-column><el-table-column label="公司名称" min-width="230" show-overflow-tooltip><template #default="{ row }"><div class="customer-name">{{ row.companyName }}</div></template></el-table-column><el-table-column label="业务类型" width="135"><template #default="{ row }">{{ optionLabel(businessTypes, row.businessType) }}</template></el-table-column><el-table-column label="订单状态" width="115" align="center"><template #default="{ row }"><el-tag :type="optionType(refundStatuses, row.status)">{{ optionLabel(refundStatuses, row.status) }}</el-tag></template></el-table-column><el-table-column label="退费金额" width="130" align="right"><template #default="{ row }"><strong class="money debt">{{ money(row.refundAmount) }}</strong></template></el-table-column><el-table-column label="退费原因" min-width="220" prop="reason" show-overflow-tooltip /><el-table-column label="操作记录" min-width="190" show-overflow-tooltip><template #default="{ row }">{{ row.reviewComment || (row.status === 'pending' ? '等待主管审核' : '-') }}</template></el-table-column><el-table-column label="操作" width="195" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openDetail(row)">详情</el-button><el-button v-if="row.status === 'pending' && canReview" link type="success" @click="review(row, 'approve')">审核</el-button><el-button v-if="row.status === 'approved' && canComplete" link type="success" @click="finish(row)">确认退款</el-button><el-button v-if="['pending','approved'].includes(row.status) && canReview" link type="danger" @click="review(row, 'reject')">驳回</el-button></template></el-table-column></el-table></div>
      <div class="pagination-row"><el-pagination v-model:current-page="page.pageNum" v-model:page-size="page.pageSize" :total="page.total" :page-sizes="[10,20,50]" layout="total, prev, pager, next, sizes" @change="loadRows" /></div>
    </section>
    <el-drawer v-model="detailVisible" class="feige-detail-drawer" size="min(720px, 94vw)" title="退费详情" destroy-on-close><template v-if="current"><el-descriptions :column="2" border><el-descriptions-item label="订单编号">{{ current.orderNo }}</el-descriptions-item><el-descriptions-item label="申请时间">{{ formatDateTime(current.createTime) }}</el-descriptions-item><el-descriptions-item label="客户名称" :span="2">{{ current.companyName }}</el-descriptions-item><el-descriptions-item label="业务人员">{{ current.salesmanName }}</el-descriptions-item><el-descriptions-item label="所属团队">{{ current.teamName || '-' }}</el-descriptions-item><el-descriptions-item label="退费金额">{{ money(current.refundAmount) }}</el-descriptions-item><el-descriptions-item label="当前状态">{{ optionLabel(refundStatuses, current.status) }}</el-descriptions-item><el-descriptions-item label="退费原因" :span="2">{{ current.reason }}</el-descriptions-item><el-descriptions-item label="审核人">{{ current.reviewerName || '-' }}</el-descriptions-item><el-descriptions-item label="审核时间">{{ formatDateTime(current.reviewTime) }}</el-descriptions-item><el-descriptions-item label="审核意见" :span="2">{{ current.reviewComment || '-' }}</el-descriptions-item></el-descriptions><div class="drawer-section"><h3>退费流程</h3><el-steps :active="refundStep(current.status)" finish-status="success"><el-step title="提交申请" /><el-step title="主管审核" /><el-step title="财务退款" /></el-steps></div></template></el-drawer>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Refresh, Search } from '@element-plus/icons-vue'
import type { FeigeRefund } from '@/api/feige-order-contract'
import { useUserStore } from '@/stores/user'
import { businessTypes, formatDateTime, money, optionLabel, optionType, refundStatuses } from './options'
import { feigeLocalDemo, feigeOrderData } from '@feige-order-data-source'
type RefundRow = FeigeRefund & { teamName?: string; businessType?: string }
const userStore = useUserStore(); const roleSet = computed(() => new Set((userStore.roles || []).flatMap((role) => [role, role.split('__')[0]]))); const canReview = computed(() => feigeLocalDemo || ['admin','super_admin','boss','manager','dept_manager','finance','finance_hq'].some((role) => roleSet.value.has(role))); const canComplete = computed(() => feigeLocalDemo || ['admin','super_admin','boss','finance','finance_hq'].some((role) => roleSet.value.has(role)))
const loading = ref(false); const rows = ref<RefundRow[]>([]); const current = ref<RefundRow | null>(null); const detailVisible = ref(false); const filters = reactive({ keyword: '', status: '', dates: [] as string[] }); const page = reactive({ pageNum: 1, pageSize: 10, total: 0 })
async function loadRows() { loading.value = true; try { const [data, orderData] = await Promise.all([feigeOrderData.refunds({ pageNum: page.pageNum, pageSize: page.pageSize, keyword: filters.keyword || undefined, status: filters.status || undefined, startDate: filters.dates[0], endDate: filters.dates[1] }), feigeOrderData.orders({ pageNum: 1, pageSize: 1000 })]); const map = new Map(orderData.records.map((item) => [item.id, item])); rows.value = data.records.map((item) => ({ ...item, teamName: map.get(item.orderId)?.teamName, businessType: map.get(item.orderId)?.businessType })); page.total = Number(data.total || 0) } finally { loading.value = false } }
function search() { page.pageNum = 1; loadRows() } function reset() { Object.assign(filters, { keyword: '', status: '', dates: [] }); search() } function openDetail(row: RefundRow) { current.value = row; detailVisible.value = true }
async function review(row: RefundRow, action: 'approve' | 'reject') { const label = action === 'approve' ? '通过' : '驳回'; const result = await ElMessageBox.prompt(`确认${label}“${row.companyName}”的退费申请？`, `${label}退费`, { inputPlaceholder: action === 'reject' ? '请填写驳回原因' : '审核意见（可选）', inputValidator: action === 'reject' ? (value) => !!String(value || '').trim() || '请填写原因' : undefined, type: action === 'approve' ? 'warning' : 'error' }); if (action === 'approve') await feigeOrderData.approveRefund(row.id, result.value); else await feigeOrderData.rejectRefund(row.id, result.value); ElMessage.success(`退费申请已${label}`); await loadRows() }
async function finish(row: RefundRow) { await ElMessageBox.confirm(`确认已向“${row.companyName}”退回 ${money(row.refundAmount)}？`, '确认完成退费', { type: 'warning' }); await feigeOrderData.completeRefund(row.id, '财务确认已退款'); ElMessage.success('退费已完成'); await loadRows() }
function refundStep(status: string) { return status === 'completed' ? 3 : status === 'approved' ? 2 : status === 'rejected' ? 1 : 1 }
onMounted(loadRows)
</script>
<style lang="scss" src="./module.scss"></style>
