<template>
  <div class="task-workbench task-workbench-page subordinate-page">
    <header class="page-head page-heading"><div class="page-title"><div class="eyebrow"><el-icon><UserFilled /></el-icon> 任务工单 · 团队执行</div><h2>下属工作视图</h2><p>主管查看授权部门内员工的提交率、完成率和未完成原因，不能越权查看其他部门。</p></div><el-tag v-if="feigeTaskLocalDemo()" type="warning" size="large" effect="dark">LOCAL-DEMO 演示数据</el-tag></header>
    <el-alert v-if="!manager && !feigeTaskLocalDemo()" title="只有主管、老板或管理员可以查看下属工作。" type="warning" show-icon :closable="false"/>
    <el-alert v-if="errorText" :title="errorText" type="error" show-icon :closable="false"/>
    <section v-if="manager || feigeTaskLocalDemo()" class="toolbar-card"><el-tree-select v-model="query.roleId" :data="roles" node-key="id" :props="treeProps" check-strictly clearable placeholder="全部角色" @change="loadRows"/><el-segmented v-model="query.cycleType" :options="cycleOptions" @change="changeCycle"/><el-date-picker v-if="query.cycleType==='day'" v-model="query.periodKey" type="date" value-format="YYYY-MM-DD" :clearable="false" @change="loadRows"/><el-date-picker v-else-if="query.cycleType==='week'" v-model="weekDate" type="week" format="YYYY 第 ww 周" :clearable="false" @change="changeWeek"/><el-date-picker v-else v-model="query.periodKey" type="month" value-format="YYYY-MM" :clearable="false" @change="loadRows"/><el-input v-model="query.keyword" clearable placeholder="搜索姓名或部门" @keyup.enter="loadRows"/><el-button type="primary" :loading="loading" @click="loadRows">查询</el-button></section>
    <section v-if="manager || feigeTaskLocalDemo()" class="metric-strip"><div><span>下属人数</span><strong>{{rows.length}}</strong></div><div><span>已提交报告</span><strong class="good">{{submittedCount}}</strong></div><div><span>未提交报告</span><strong class="danger">{{rows.length-submittedCount}}</strong></div><div><span>平均完成率</span><strong>{{averageRate}}%</strong></div></section>
    <section v-if="manager || feigeTaskLocalDemo()" class="content-card"><el-table :data="rows" v-loading="loading" row-key="userId"><el-table-column prop="userName" label="员工" min-width="140"/><el-table-column prop="deptName" label="部门" min-width="150"/><el-table-column prop="roleName" label="角色" min-width="130"/><el-table-column label="任务进度" min-width="230"><template #default="{row}"><el-progress :percentage="row.completionRate" :format="()=>`${row.done}/${row.total}`" :status="row.completionRate>=100?'success':undefined"/></template></el-table-column><el-table-column label="报告" width="100"><template #default="{row}"><el-tag :type="row.submitted?'success':'danger'">{{row.submitted?'已提交':'未提交'}}</el-tag></template></el-table-column><el-table-column label="风险" min-width="140"><template #default="{row}"><el-tag v-if="!row.submitted" type="danger" effect="plain">缺报</el-tag><el-tag v-else-if="row.completionRate<80" type="warning" effect="plain">完成率偏低</el-tag><span v-else class="good">正常</span></template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="openDetail(row)">查看详情</el-button></template></el-table-column></el-table></section>
    <SubordinateDetailDrawer ref="drawerRef"/>
  </div>
</template>
<script setup lang="ts">
import{computed,onMounted,reactive,ref}from'vue';import{UserFilled}from'@element-plus/icons-vue';import type{RoleTreeNode,SubordinateDetail,SubordinateRow}from'@/api/feige-task';import{feigeTaskData,feigeTaskLocalDemo}from'./data-source';import SubordinateDetailDrawer from'./components/SubordinateDetailDrawer.vue';import'./common.scss'
const now=new Date();function pad(n:number){return String(n).padStart(2,'0')}function dateKey(d:Date){return`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}function weekKey(d:Date){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())),day=x.getUTCDay()||7;x.setUTCDate(x.getUTCDate()+4-day);const start=new Date(Date.UTC(x.getUTCFullYear(),0,1)),week=Math.ceil((((x.getTime()-start.getTime())/86400000)+1)/7);return`${x.getUTCFullYear()}-W${pad(week)}`}
const query=reactive({roleId:undefined as number|undefined,cycleType:'day',periodKey:dateKey(now),keyword:'',pageNum:1,pageSize:200}),weekDate=ref(now),roles=ref<RoleTreeNode[]>([]),rows=ref<SubordinateRow[]>([]),loading=ref(false),manager=ref(false),errorText=ref(''),drawerRef=ref<InstanceType<typeof SubordinateDetailDrawer>>()
const treeProps={label:'name',children:'children',value:'id'},cycleOptions=[{label:'每日',value:'day'},{label:'每周',value:'week'},{label:'每月',value:'month'}]
function unwrap<T>(v:any):T{return(v?.data?.data??v?.data??v)as T}const submittedCount=computed(()=>rows.value.filter(r=>r.submitted).length),averageRate=computed(()=>rows.value.length?Math.round(rows.value.reduce((s,r)=>s+r.completionRate,0)/rows.value.length):0)
async function loadRows(){loading.value=true;errorText.value='';try{const r=unwrap<any>(await feigeTaskData.subordinates({...query}));rows.value=r?.records||[]}catch{rows.value=[];errorText.value='下属工作数据加载失败，生产环境不会展示演示人员。'}finally{loading.value=false}}
async function loadRoles(){try{roles.value=unwrap<RoleTreeNode[]>(await feigeTaskData.roleTree())||[]}catch{roles.value=[]}}
async function loadCapabilities(){try{manager.value=Boolean((await feigeTaskData.capabilities())?.manager)}catch{manager.value=false}}
function changeCycle(){if(query.cycleType==='day')query.periodKey=dateKey(now);else if(query.cycleType==='week')query.periodKey=weekKey(weekDate.value);else query.periodKey=`${now.getFullYear()}-${pad(now.getMonth()+1)}`;loadRows()}function changeWeek(d:Date){query.periodKey=weekKey(new Date(d));loadRows()}
function openDetail(row:SubordinateRow){drawerRef.value?.open(async()=>unwrap<SubordinateDetail>(await feigeTaskData.subordinateDetail({userId:row.userId,cycleType:query.cycleType,periodKey:query.periodKey})))}
onMounted(async()=>{await loadCapabilities();if(manager.value||feigeTaskLocalDemo()){loadRoles();loadRows()}})
</script>
<style scoped lang="scss">.subordinate-page{display:grid;gap:16px}.toolbar-card{display:grid;grid-template-columns:220px auto 190px minmax(180px,1fr) auto;gap:10px;background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px}.metric-strip{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.metric-strip div{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:16px;display:grid;gap:5px}.metric-strip span{color:#6b7280}.metric-strip strong{font-size:26px}.good{color:#16a34a}.danger{color:#dc2626}.content-card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:14px}@media(max-width:1000px){.toolbar-card{grid-template-columns:1fr 1fr}.metric-strip{grid-template-columns:1fr 1fr}}</style>
