-- =============================================================================
-- V141  审单中心:提单提交后统一走"合同审理→财务到款确认→办事接收→办理完毕"四节点审单。
--       多态关联各类提单(order_type+order_id),审单主表冗余快照(客户/金额/销售/部门)。
--       6 张表:主表 + 流转记录 + 四节点结构化明细。不改动现有提单表。
-- =============================================================================
CREATE TABLE IF NOT EXISTS `biz_order_review` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_no` VARCHAR(32) DEFAULT NULL COMMENT '审单编号(SD+日期+流水)',
  `order_type` VARCHAR(16) DEFAULT NULL COMMENT '提单类型:bookkeeping/gs/seal/address/order',
  `order_id` BIGINT DEFAULT NULL COMMENT '关联提单ID(多态)',
  `order_no` VARCHAR(64) DEFAULT NULL COMMENT '原提单编号(快照)',
  `customer_id` BIGINT DEFAULT NULL COMMENT '客户ID',
  `customer_name` VARCHAR(200) DEFAULT NULL COMMENT '客户名称(快照)',
  `business_type` VARCHAR(64) DEFAULT NULL COMMENT '业务类型描述',
  `receivable_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '应收金额(快照)',
  `received_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '已确认到账金额',
  `sales_user_id` BIGINT DEFAULT NULL COMMENT '销售/发起人ID',
  `sales_name` VARCHAR(64) DEFAULT NULL COMMENT '销售/发起人姓名',
  `handler_user_id` BIGINT DEFAULT NULL COMMENT '办事人员ID',
  `handler_name` VARCHAR(64) DEFAULT NULL COMMENT '办事人员姓名',
  `dept_id` BIGINT DEFAULT NULL COMMENT '归属部门ID',
  `current_node` VARCHAR(16) DEFAULT NULL COMMENT '当前节点:CONTRACT/PAYMENT/ACCEPT/PROCESS/COMPLETE',
  `review_status` VARCHAR(24) DEFAULT NULL COMMENT '审单总状态(DRAFT..COMPLETED/VOIDED)',
  `deadline` DATETIME DEFAULT NULL COMMENT '当前节点截止时间',
  `submitted_at` DATETIME DEFAULT NULL COMMENT '提交审单时间',
  `completed_at` DATETIME DEFAULT NULL COMMENT '全部完成时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_tenant_no` (`tenant_id`,`review_no`),
  UNIQUE KEY `uk_review_tenant_order` (`tenant_id`,`order_type`,`order_id`),
  KEY `idx_review_tenant_deadline` (`tenant_id`,`deadline`,`id`),
  KEY `idx_review_tenant_status_deadline` (`tenant_id`,`review_status`,`deadline`,`id`),
  KEY `idx_review_tenant_dept_status` (`tenant_id`,`dept_id`,`review_status`,`deadline`),
  KEY `idx_review_tenant_sales_status` (`tenant_id`,`sales_user_id`,`review_status`),
  KEY `idx_review_tenant_handler_status` (`tenant_id`,`handler_user_id`,`review_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审单主表';

CREATE TABLE IF NOT EXISTS `biz_order_review_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_id` BIGINT NOT NULL COMMENT '审单主表ID',
  `order_id` BIGINT DEFAULT NULL COMMENT '提单ID',
  `order_type` VARCHAR(16) DEFAULT NULL COMMENT '提单类型',
  `node_code` VARCHAR(16) DEFAULT NULL COMMENT '节点编码',
  `node_name` VARCHAR(32) DEFAULT NULL COMMENT '节点名称',
  `action` VARCHAR(24) DEFAULT NULL COMMENT '动作',
  `result` VARCHAR(24) DEFAULT NULL COMMENT '处理结果',
  `operator_id` BIGINT DEFAULT NULL COMMENT '操作人ID',
  `operator_name` VARCHAR(64) DEFAULT NULL COMMENT '操作人姓名',
  `opinion` VARCHAR(1000) DEFAULT NULL COMMENT '审理意见/退回原因',
  `attachments` VARCHAR(2000) DEFAULT NULL COMMENT '附件(JSON数组)',
  `before_status` VARCHAR(24) DEFAULT NULL COMMENT '操作前状态',
  `after_status` VARCHAR(24) DEFAULT NULL COMMENT '操作后状态',
  `operated_at` DATETIME DEFAULT NULL COMMENT '操作时间',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  KEY `idx_review_record_tenant_time` (`tenant_id`,`review_id`,`operated_at`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审单流转记录';

CREATE TABLE IF NOT EXISTS `biz_order_review_contract` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_id` BIGINT NOT NULL COMMENT '审单主表ID',
  `order_id` BIGINT DEFAULT NULL COMMENT '提单ID',
  `customer_info_ok` TINYINT DEFAULT NULL COMMENT '客户信息是否正确:0否1是',
  `business_type` VARCHAR(64) DEFAULT NULL COMMENT '业务类型',
  `contract_file` VARCHAR(2000) DEFAULT NULL COMMENT '合同附件(JSON数组)',
  `contract_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '合同金额',
  `service_period` VARCHAR(64) DEFAULT NULL COMMENT '服务周期',
  `sales_remark` VARCHAR(500) DEFAULT NULL COMMENT '销售备注',
  `reviewer_id` BIGINT DEFAULT NULL COMMENT '合同审理人ID',
  `reviewer_name` VARCHAR(64) DEFAULT NULL COMMENT '合同审理人',
  `review_time` DATETIME DEFAULT NULL COMMENT '审理时间',
  `review_result` VARCHAR(16) DEFAULT NULL COMMENT '审理结果:pass/reject',
  `review_remark` VARCHAR(500) DEFAULT NULL COMMENT '审理备注',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_contract_tenant` (`tenant_id`,`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='合同审理明细';

CREATE TABLE IF NOT EXISTS `biz_order_review_payment` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_id` BIGINT NOT NULL COMMENT '审单主表ID',
  `order_id` BIGINT DEFAULT NULL COMMENT '提单ID',
  `receivable_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '应收金额',
  `received_amount` DECIMAL(14,2) DEFAULT NULL COMMENT '确认到账金额',
  `received_date` DATE DEFAULT NULL COMMENT '到账日期',
  `payment_method` VARCHAR(32) DEFAULT NULL COMMENT '收款方式',
  `receipt_id` BIGINT DEFAULT NULL COMMENT '关联收款记录ID(预留)',
  `receipt_no` VARCHAR(64) DEFAULT NULL COMMENT '关联收款单号(预留)',
  `voucher` VARCHAR(2000) DEFAULT NULL COMMENT '到账凭证(JSON数组)',
  `payer` VARCHAR(200) DEFAULT NULL COMMENT '客户付款方',
  `confirmer_id` BIGINT DEFAULT NULL COMMENT '财务确认人ID',
  `confirmer_name` VARCHAR(64) DEFAULT NULL COMMENT '财务确认人',
  `confirm_time` DATETIME DEFAULT NULL COMMENT '财务确认时间',
  `finance_remark` VARCHAR(500) DEFAULT NULL COMMENT '财务备注',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_payment_tenant` (`tenant_id`,`review_id`),
  KEY `idx_review_payment_confirmer` (`tenant_id`,`confirmer_id`,`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='财务到款确认明细';

CREATE TABLE IF NOT EXISTS `biz_order_review_accept` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_id` BIGINT NOT NULL COMMENT '审单主表ID',
  `order_id` BIGINT DEFAULT NULL COMMENT '提单ID',
  `handler_user_id` BIGINT DEFAULT NULL COMMENT '办事人员ID',
  `handler_name` VARCHAR(64) DEFAULT NULL COMMENT '办事人员',
  `dept_id` BIGINT DEFAULT NULL COMMENT '所属部门ID',
  `dept_name` VARCHAR(64) DEFAULT NULL COMMENT '所属部门',
  `accept_time` DATETIME DEFAULT NULL COMMENT '正式接收时间',
  `expected_complete_time` DATETIME DEFAULT NULL COMMENT '预计完成时间',
  `materials_ready` TINYINT DEFAULT NULL COMMENT '资料是否齐全:0否1是',
  `accept_remark` VARCHAR(500) DEFAULT NULL COMMENT '接收备注',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_accept_tenant` (`tenant_id`,`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='办事人员接收确认明细';

CREATE TABLE IF NOT EXISTS `biz_order_review_complete` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `review_id` BIGINT NOT NULL COMMENT '审单主表ID',
  `order_id` BIGINT DEFAULT NULL COMMENT '提单ID',
  `complete_time` DATETIME DEFAULT NULL COMMENT '办理完成时间',
  `result_desc` VARCHAR(1000) DEFAULT NULL COMMENT '办理结果说明',
  `complete_voucher` VARCHAR(2000) DEFAULT NULL COMMENT '完成凭证附件(JSON数组)',
  `submitter_id` BIGINT DEFAULT NULL COMMENT '完成提交人ID',
  `submitter_name` VARCHAR(64) DEFAULT NULL COMMENT '完成提交人',
  `confirmer_id` BIGINT DEFAULT NULL COMMENT '完成确认人ID',
  `confirmer_name` VARCHAR(64) DEFAULT NULL COMMENT '完成确认人',
  `confirm_time` DATETIME DEFAULT NULL COMMENT '完成确认时间',
  `complete_remark` VARCHAR(500) DEFAULT NULL COMMENT '完成备注',
  `create_by` BIGINT DEFAULT NULL COMMENT '创建人',
  `update_by` BIGINT DEFAULT NULL COMMENT '更新人',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` INT DEFAULT 0 COMMENT '逻辑删除',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_review_complete_tenant` (`tenant_id`,`review_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='办理完毕确认明细';
