-- 任务工作台隔离数据域。
-- 仅新增 feige_task_* 表；不修改现有业务表、角色、菜单或生产数据。

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS feige_task_business (
    id BIGINT NOT NULL AUTO_INCREMENT,
    order_id BIGINT DEFAULT NULL COMMENT '可空关联 feige_order.id，仅作业务引用',
    order_no VARCHAR(64) DEFAULT NULL,
    company_name VARCHAR(200) NOT NULL,
    business_type VARCHAR(64) DEFAULT NULL,
    priority VARCHAR(32) DEFAULT NULL,
    task_status VARCHAR(32) NOT NULL DEFAULT 'pending_manager_audit',
    manager_review_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    manager_reviewer_id BIGINT DEFAULT NULL,
    manager_reviewer_name VARCHAR(100) DEFAULT NULL,
    manager_review_time DATETIME DEFAULT NULL,
    manager_review_remark VARCHAR(1000) DEFAULT NULL,
    assign_type VARCHAR(32) DEFAULT NULL,
    owner_id BIGINT DEFAULT NULL,
    owner_name VARCHAR(100) DEFAULT NULL,
    dept_id BIGINT DEFAULT NULL,
    received_by BIGINT DEFAULT NULL,
    received_by_name VARCHAR(100) DEFAULT NULL,
    received_time DATETIME DEFAULT NULL,
    cost_category VARCHAR(100) DEFAULT NULL,
    cost_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    order_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    received_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    deadline DATETIME DEFAULT NULL,
    handover_by BIGINT DEFAULT NULL,
    handover_by_name VARCHAR(100) DEFAULT NULL,
    handover_time DATETIME DEFAULT NULL,
    handover_status VARCHAR(32) DEFAULT NULL,
    handover_to_id BIGINT DEFAULT NULL,
    handover_to_name VARCHAR(100) DEFAULT NULL,
    business_owner_id BIGINT DEFAULT NULL,
    business_owner_name VARCHAR(100) DEFAULT NULL,
    completed_time DATETIME DEFAULT NULL,
    exception_reason VARCHAR(1000) DEFAULT NULL,
    remarks VARCHAR(1000) DEFAULT NULL,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_business_scope (tenant_id, task_status, dept_id, owner_id, deleted),
    KEY idx_ft_business_order (tenant_id, order_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务任务八状态工作台';

CREATE TABLE IF NOT EXISTS feige_task_operation_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    domain_type VARCHAR(32) NOT NULL,
    business_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    from_status VARCHAR(32) DEFAULT NULL,
    to_status VARCHAR(32) DEFAULT NULL,
    operator_id BIGINT NOT NULL,
    operator_name VARCHAR(100) NOT NULL,
    detail VARCHAR(1000) DEFAULT NULL,
    payload_json LONGTEXT DEFAULT NULL,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_log_business (tenant_id, domain_type, business_id, create_time, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='任务统一操作日志';

CREATE TABLE IF NOT EXISTS feige_task_audit_process (
    id BIGINT NOT NULL AUTO_INCREMENT,
    process_code VARCHAR(64) NOT NULL,
    process_name VARCHAR(150) NOT NULL,
    task_type VARCHAR(32) NOT NULL COMMENT 'once/recurring/project_dept/special',
    business_type_code VARCHAR(64) DEFAULT NULL,
    description VARCHAR(1000) DEFAULT NULL,
    enabled TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_audit_process_code (tenant_id, process_code),
    KEY idx_ft_audit_process_type (tenant_id, task_type, business_type_code, enabled, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批任务流程';

CREATE TABLE IF NOT EXISTS feige_task_audit_step (
    id BIGINT NOT NULL AUTO_INCREMENT,
    process_id BIGINT NOT NULL,
    step_order INT NOT NULL,
    step_name VARCHAR(150) NOT NULL,
    required_role_key VARCHAR(64) DEFAULT NULL,
    assignee_mode VARCHAR(32) NOT NULL COMMENT 'role/specific/owner',
    required_user_id BIGINT DEFAULT NULL,
    allow_batch TINYINT NOT NULL DEFAULT 0,
    final_step TINYINT NOT NULL DEFAULT 0,
    form_schema_json LONGTEXT DEFAULT NULL,
    indicator_schema_json LONGTEXT DEFAULT NULL,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_audit_step_order (tenant_id, process_id, step_order),
    KEY idx_ft_audit_step_process (tenant_id, process_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='审批流程步骤';

CREATE TABLE IF NOT EXISTS feige_task_audit_instance (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_no VARCHAR(64) NOT NULL,
    order_id BIGINT DEFAULT NULL COMMENT '可空关联 feige_order.id，仅作业务引用',
    order_no VARCHAR(64) DEFAULT NULL,
    company_name VARCHAR(200) NOT NULL,
    task_type VARCHAR(32) NOT NULL,
    business_type_code VARCHAR(64) DEFAULT NULL,
    business_type_name VARCHAR(150) DEFAULT NULL,
    process_id BIGINT NOT NULL,
    process_code VARCHAR(64) NOT NULL,
    process_name VARCHAR(150) NOT NULL,
    step_id BIGINT DEFAULT NULL,
    step_order INT DEFAULT NULL,
    total_steps INT NOT NULL DEFAULT 1,
    step_name VARCHAR(150) DEFAULT NULL,
    task_status VARCHAR(32) NOT NULL DEFAULT 'pending',
    audit_result VARCHAR(32) DEFAULT NULL,
    assigned_user_id BIGINT DEFAULT NULL,
    assigned_user_name VARCHAR(100) DEFAULT NULL,
    required_role_key VARCHAR(64) DEFAULT NULL,
    business_owner_id BIGINT NOT NULL,
    business_owner_name VARCHAR(100) NOT NULL,
    service_person_id BIGINT DEFAULT NULL,
    service_person_name VARCHAR(100) DEFAULT NULL,
    dept_id BIGINT DEFAULT NULL,
    scope_type VARCHAR(32) DEFAULT NULL,
    team_name VARCHAR(150) DEFAULT NULL,
    region VARCHAR(150) DEFAULT NULL,
    amount DECIMAL(14,2) DEFAULT NULL,
    expense_amount DECIMAL(14,2) DEFAULT NULL,
    start_month VARCHAR(16) DEFAULT NULL,
    end_month VARCHAR(16) DEFAULT NULL,
    remarks VARCHAR(1000) DEFAULT NULL,
    audit_data_json LONGTEXT DEFAULT NULL,
    audit_remark VARCHAR(1000) DEFAULT NULL,
    reject_reason VARCHAR(1000) DEFAULT NULL,
    audit_time DATETIME DEFAULT NULL,
    audit_user_id BIGINT DEFAULT NULL,
    audit_user_name VARCHAR(100) DEFAULT NULL,
    process_snapshot_json LONGTEXT DEFAULT NULL,
    final_confirm TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ft_audit_no (tenant_id, task_no),
    KEY idx_ft_audit_scope (tenant_id, task_type, task_status, dept_id, business_owner_id, deleted),
    KEY idx_ft_audit_assignee (tenant_id, assigned_user_id, required_role_key, task_status, deleted),
    KEY idx_ft_audit_order (tenant_id, order_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='一次性周期项目部门专项审批任务';

CREATE TABLE IF NOT EXISTS feige_task_workflow_template (
    id BIGINT NOT NULL AUTO_INCREMENT,
    role_id BIGINT NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    cycle_type VARCHAR(16) NOT NULL COMMENT 'day/week/month',
    task_name VARCHAR(200) NOT NULL,
    completion_standard VARCHAR(1000) DEFAULT NULL,
    work_content LONGTEXT DEFAULT NULL,
    detail_fields_json LONGTEXT DEFAULT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    enabled TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_wf_template_role (tenant_id, role_id, cycle_type, enabled, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作计划模板';

CREATE TABLE IF NOT EXISTS feige_task_workflow_item (
    id BIGINT NOT NULL AUTO_INCREMENT,
    template_id BIGINT DEFAULT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    role_id BIGINT DEFAULT NULL,
    role_name VARCHAR(100) DEFAULT NULL,
    dept_id BIGINT DEFAULT NULL,
    cycle_type VARCHAR(16) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    task_name VARCHAR(200) NOT NULL,
    completion_standard VARCHAR(1000) DEFAULT NULL,
    work_content LONGTEXT DEFAULT NULL,
    source VARCHAR(32) NOT NULL DEFAULT 'template',
    detail_fields_json LONGTEXT DEFAULT NULL,
    work_detail_json LONGTEXT DEFAULT NULL,
    done TINYINT NOT NULL DEFAULT 0,
    done_time DATETIME DEFAULT NULL,
    undone_reason VARCHAR(1000) DEFAULT NULL,
    remark VARCHAR(1000) DEFAULT NULL,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    active_identity TINYINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN 1 ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ft_wf_item_identity (tenant_id, user_id, template_id, cycle_type, period_key, active_identity),
    KEY idx_ft_wf_item_scope (tenant_id, dept_id, user_id, cycle_type, period_key, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作计划任务实例';

CREATE TABLE IF NOT EXISTS feige_task_workflow_report (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    dept_id BIGINT DEFAULT NULL,
    cycle_type VARCHAR(16) NOT NULL,
    period_key VARCHAR(32) NOT NULL,
    total_count INT NOT NULL DEFAULT 0,
    done_count INT NOT NULL DEFAULT 0,
    completion_rate DECIMAL(7,2) NOT NULL DEFAULT 0.00,
    summary LONGTEXT DEFAULT NULL,
    undone_details_json LONGTEXT DEFAULT NULL,
    submitted_at DATETIME DEFAULT NULL,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    active_identity TINYINT GENERATED ALWAYS AS (CASE WHEN deleted = 0 THEN 1 ELSE NULL END) STORED,
    PRIMARY KEY (id),
    UNIQUE KEY uk_ft_wf_report_identity (tenant_id, user_id, cycle_type, period_key, active_identity),
    KEY idx_ft_wf_report_scope (tenant_id, dept_id, cycle_type, period_key, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作计划报表与总结';

CREATE TABLE IF NOT EXISTS feige_task_workflow_required (
    id BIGINT NOT NULL AUTO_INCREMENT,
    target_type VARCHAR(16) NOT NULL COMMENT 'user/role',
    target_id BIGINT NOT NULL,
    target_name VARCHAR(150) NOT NULL,
    remark VARCHAR(1000) DEFAULT NULL,
    active TINYINT NOT NULL DEFAULT 1,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_wf_required_target (tenant_id, target_type, target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='工作计划必报范围';

CREATE TABLE IF NOT EXISTS feige_task_goal (
    id BIGINT NOT NULL AUTO_INCREMENT,
    goal_name VARCHAR(200) NOT NULL,
    goal_type VARCHAR(32) NOT NULL COMMENT 'month/quarter/half_year/year',
    role_id BIGINT DEFAULT NULL,
    role_name VARCHAR(100) DEFAULT NULL,
    user_id BIGINT DEFAULT NULL,
    user_name VARCHAR(100) DEFAULT NULL,
    owner_id BIGINT NOT NULL,
    dept_id BIGINT DEFAULT NULL,
    period_year INT NOT NULL,
    period_index INT DEFAULT NULL,
    period_key VARCHAR(32) NOT NULL,
    metric_name VARCHAR(100) DEFAULT NULL,
    target_value DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    actual_value DECIMAL(16,2) NOT NULL DEFAULT 0.00,
    performance_target DECIMAL(16,2) DEFAULT NULL,
    performance_actual DECIMAL(16,2) DEFAULT NULL,
    bookkeeping_target DECIMAL(16,2) DEFAULT NULL,
    bookkeeping_actual DECIMAL(16,2) DEFAULT NULL,
    renewal_target DECIMAL(16,2) DEFAULT NULL,
    renewal_actual DECIMAL(16,2) DEFAULT NULL,
    unit VARCHAR(32) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    goal_desc VARCHAR(2000) DEFAULT NULL,
    completion_note VARCHAR(1000) DEFAULT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_goal_scope (tenant_id, dept_id, owner_id, status, deleted),
    KEY idx_ft_goal_period (tenant_id, period_year, goal_type, period_key, deleted),
    KEY idx_ft_goal_target (tenant_id, role_id, user_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='目标设置';

CREATE TABLE IF NOT EXISTS feige_task_goal_plan (
    id BIGINT NOT NULL AUTO_INCREMENT,
    goal_id BIGINT NOT NULL,
    plan_name VARCHAR(150) NOT NULL,
    plan_desc VARCHAR(2000) DEFAULT NULL,
    start_date DATE DEFAULT NULL,
    end_date DATE DEFAULT NULL,
    performance_target DECIMAL(16,2) DEFAULT NULL,
    performance_actual DECIMAL(16,2) DEFAULT NULL,
    bookkeeping_target DECIMAL(16,2) DEFAULT NULL,
    bookkeeping_actual DECIMAL(16,2) DEFAULT NULL,
    renewal_target DECIMAL(16,2) DEFAULT NULL,
    renewal_actual DECIMAL(16,2) DEFAULT NULL,
    sort_no INT NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'active',
    version INT NOT NULL DEFAULT 0,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_goal_plan (tenant_id, goal_id, sort_no, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='目标计划';

CREATE TABLE IF NOT EXISTS feige_task_goal_plan_user (
    id BIGINT NOT NULL AUTO_INCREMENT,
    plan_id BIGINT NOT NULL,
    goal_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    dept_id BIGINT DEFAULT NULL,
    target_value DECIMAL(16,2) DEFAULT NULL,
    actual_value DECIMAL(16,2) DEFAULT NULL,
    create_time DATETIME DEFAULT NULL, update_time DATETIME DEFAULT NULL,
    create_by BIGINT DEFAULT NULL, update_by BIGINT DEFAULT NULL,
    deleted TINYINT NOT NULL DEFAULT 0, tenant_id BIGINT DEFAULT NULL,
    PRIMARY KEY (id),
    KEY idx_ft_goal_plan_user_identity (tenant_id, plan_id, user_id),
    KEY idx_ft_goal_plan_user_scope (tenant_id, goal_id, dept_id, user_id, deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='目标计划人员分解';
